### ISSUE TITLE
Changing Position of Full Screen button dynamically 

### ISSUE THREAD

**Issue by Stephen-Jawahar** [Leaflet/Leaflet.fullscreen#93] opened 2019-04-10 04:30 UTC
Hi, I am new to this, do I need to change the position type in the node module code itself or is there a way to change it dynamically for each instance when it is used. If there is a way to change it dynamically for each instance of use in an application, can you give me the code to implement it that way.

thanks

**Comment by IvanSanchez** [comment] 2019-04-10 13:52
Duplicate of #92

**Closed as completed by IvanSanchez** 2019-04-10 13:52 UTC
