### ISSUE TITLE
demo page broken

### ISSUE THREAD

**Issue by letmaik** [Leaflet/Leaflet.fullscreen#38] opened 2015-07-06 05:48 UTC
Tested in Firefox.

**Comment by yohanboniface** [comment] 2015-07-06 07:58
Are you talking about http://leaflet.github.io/Leaflet.fullscreen/ ? It seems to work without issue here (Firefox 38, Ubuntu 15.04).
Can you be a bit more specific on what's broken?

**Comment by Eschon** [comment] 2015-07-06 08:34
@neothemachine I think you confused this repository with [brunob/leaflet.fullscreen](https://github.com/brunob/leaflet.fullscreen) because their [demo page](http://brunob.github.io/leaflet.fullscreen/) really seems to be broken.

**Edit:** I just saw that you also opened an issue over there, did you have any problem with this repositories demo page? It works fine for me in Safari.

**Comment by letmaik** [comment] 2015-07-06 08:37
It happens when I access it via https: 
https://leaflet.github.io/Leaflet.fullscreen/
I just realized that the HTTPS Everywhere browser plugin is doing the 
automatic switch from http to https.
It seems that the leafletjs cdn has an invalid SSL certificate, 
otherwise it would be as simple as leaving off the protocol when 
including leaflet in your html: 
//cdn.leafletjs.com/leaflet-0.7.3/leaflet.js Any ideas?

**Comment by Eschon** [comment] 2015-07-06 08:39
True, with https it works for me in latest Safari but is broken in FF38.

**Comment by letmaik** [comment] 2015-07-06 08:51
Here's the SSL issue: https://github.com/Leaflet/Leaflet/issues/1824
Well, I guess a possible solution would be to just use the cloudflare cdn since it supports https:
`//cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.js`
Ideally though leaflets cdn host should support https which actually seems possible according to http://webmasters.stackexchange.com/a/30060

**Comment by jfirebaugh** [comment] 2015-07-06 16:45
Closing here since the issue is with SSL / HTTPS Everywhere. I've reopened https://github.com/Leaflet/Leaflet/issues/1824 since it should be possible to provide https support on the CDN now.

**Closed as completed by jfirebaugh** 2015-07-06 16:45 UTC
